### ISSUE TITLE
Recruitment web app - Implement login form

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#10]
- Implement home#index with login form
- Use bootstrap https://getbootstrap.com/
<img width="954" alt="Screen Shot 2023-07-05 at 16 37 08" src="https://github.com/HopeeSolutionsRuby/demo-app/assets/115602568/7235325f-61e1-41ef-a58e-ff63e2a02cdd">

**Comment by DucNguyen0812** [comment]
-Requirement Implement home#index with login form
-Duc's Tasks:
   +read bootstrap document
   +create home controller and include index action
   +include bootstrap in the project
   +implement the login and password input
   
-Priya's tasks:
   +read bootstrap document
   +implement the "forgot password?" link
   +modify font and colors
   +refactor code
   
Estimate time:
   +analyze requirement and assign tasks : 10 min
   +implement the form: 1 hour
   +test, refactor and review,fix bug: 1 hour
   +buffer : 20 mins
