### ISSUE TITLE
Recruitment web app - Account

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#11]
- Implement Account
  - email
  - password
  - avatar (medium: 250x250, small: 50x50)
  - phone
  - role
- Account's role: one of (administrator, employer, employee)
- Allow login with account:
  - administrator -> go to administrator dashboard
  - employer -> go to employer dashboard
  - employee -> go to employee dashboard

Note: use [devise](https://github.com/heartcombo/devise) and [carrierwave](https://github.com/carrierwaveuploader/carrierwave)

**Comment by longlh-dev** [comment]
Long Tasks:
- Create a migration file to create the account table with using devise
- Create account model with given fields, write vadidation and callback

Tu Tasks:
- Develop the feature for account to upload their avatar by using a file upload library such as 	CarrierWave 
- Generate 2 version of avatar (medium: 250x250, small: 50x50)

Vy Tasks:
- Redirect after login with each roles

**Comment by longlh-dev** [comment]
Estimate time: 
- analyze requirement and assign tasks : 10 min
- Long tasks: 2 hours
- Tu tasks: 2 hours
- Vy task: 2 hours
- test, refactor code: 1 hour
- buffer: 1 hour
