### ISSUE TITLE
Recruitment web app - Implement administrator layout

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#12]
- Use bootstrap
- Left menu:
  - Accounts
  - Employees
  - Employers
  - ...
- Layout
<img width="1505" alt="Screen Shot 2023-07-05 at 16 58 35" src="https://github.com/HopeeSolutionsRuby/demo-app/assets/115602568/46376434-b914-4d84-b7d5-821317bf8ac7">

**Comment by jjjsss3** [comment]
- Long: 
  + 2 hour - Draw mockup 
     * Note: Design the layout for the component: left menu, header, footer, logo
   + 2 hour - Implement Header and Footer (pay attention to responsive)
     * Note: Use bootstrap
- Vy:
  + 2 hour - Init Structure of Master Layout for administrator
     * Note: Split the layout with each components have designed before
  + 2 hour - Implement Left Menu (pay attention to responsive)
     * Note: Use bootstrap
- Test, refactor code: 1 hour
- Buffer : 2 hours

**Comment by longlh-dev** [comment]
mockup for admin layout 
![image](https://github.com/HopeeSolutionsRuby/demo-app/assets/101177931/ae74cef4-792c-4e4a-ba9d-3aaa30199576)
