### ISSUE TITLE
Recruitment web app - administrator - CRUD account

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#13]

**Comment by tunh-dev1** [comment]
Priya: 

  1 hour - Add link to the left menu ( waiting for issue #12 )
  2 hours - Add sample data for account ( using FactoryBot and Faker gem ) 

    FactoryBot: https://github.com/thoughtbot/factory_bot_rails
    Faker: https://github.com/faker-ruby/faker

Đức:

  3 hours - Implement Create action and Sign up form for account :

    - Add a select field to choose employee or employer
    - Use bootstrap https://getbootstrap.com/
   <img  src="https://github.com/HopeeSolutionsRuby/demo-app/assets/102434123/edb72baf-c345-41dd-9003-bd473e6bf93d">

    
                                    Mockup for Sign up account
    

  2 hours - Add Update and Delete action account for admins 

    Note : Delete - Maybe add a status column to account and admin can block account 

Tú: 

  1 hour - Add Read Action and simple table for accounts ( employee, employer )

      Note : format to HTML and JSON 

  2 hours - Add Pagination and Search ( using gem like Ransack and Pagy ) and use AJAX for this task. 

    Ransack : https://github.com/activerecord-hackery/ransack

    Pagy : https://github.com/ddnexus/pagy

  2 hours  - Add permission - only admin can access  ( using Pundit gem )

    Pundit : https://github.com/varvet/pundit

Test, refactor code: 1 hour

Buffer : 2 hours

**Comment by KhoaNDAHopee** [comment]
Update:
- Allow the admin can update their profile (on top right header)
<img width="217" alt="Screen Shot 2023-07-13 at 10 00 39" src="https://github.com/HopeeSolutionsRuby/demo-app/assets/115602568/5c8b87d2-59cf-4886-8875-b3541f281a51">
