### ISSUE TITLE
Recruitment web app - administrator - CRUD employee

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#18]

**Comment by jjjsss3** [comment]
Vy: 

- Create Migration and Model for Employees and Seed some data with gem Faker
    - Note:
        - Accounts 1 - n Employees
        - Notice validation, callback for field
        - Create field of employees: may be a reference below
    
- Implement Read action(index)
    - Notice about ajax

![Screenshot from 2023-07-12 09-25-59](https://github.com/HopeeSolutionsRuby/demo-app/assets/73769239/1ed1bfc6-8772-453e-b5a6-eb3379d33ffd)


@longhoangcoder

- Implement Create action
    - Note: can create a simple UI to interact or rails console
- Implement Update action
    - Note: can create a simple UI to interact or rails console
    - Notice callback if need

@Priyarekah

- Implement Show action for each employee
    - Note: show the information about employee and their account, may be use rails console to see the data or make a simple UI or return json
- Implement Delete action
    - Note: if delete, make it in accounts too

**Comment by jjjsss3** [comment]
Vy: 

- 2 hours: Create Migration and Model for Employees and Seed some data with gem Faker
    - Note:
        - Accounts 1 - 1 Employees
        - Notice validation, callback for field
        - Create field of employees: may be a reference below
    
- 3 hours: Implement Read action(index)
    - Notice about ajax

![Screenshot from 2023-07-12 10-37-08](https://github.com/HopeeSolutionsRuby/demo-app/assets/73769239/b7cb4a80-5c20-4f62-9c3b-802393dab35e)

@longhoangcoder :

- 2 hours: Implement Create action
    - Note: can create a simple UI to interact or rails console
- 2 hours: Implement Update action
    - Note: can create a simple UI to interact or rails console
    - Notice callback if need

@Priyarekah :

- 2 hours: Implement Show action for each employee
    - Note: show the information about employee and their account, may be use rails console to see the data or make a simple UI or return json
- 2 hours: Implement Delete action
    - Note: if delete, make it in accounts too
    
Test, refactor code: 2 hours
Buffer : 3 hours
