### ISSUE TITLE
Recruitment web app - administrator - CRUD employer

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#19]

**Comment by DucNguyen0812** [comment]
Tu:

**Comment by DucNguyen0812** [comment]
@Tu: 
  -2 hours: Create Association between employer and accounts (1-n)
  -2 hours: Implement Read employer list and show employer information

      Note: 
      +add more field to employer db (follow database schema)
      +Maybe add active state to employer
      
@Duc:
  -2 hours: Create simple UI and do Create/Update employer
  -2 hours: implement Destroy employer account

      Note:  +Add confirm message when destroy an account
      
 Test and Refactor code : 2 hours 
 Buffer: 2 hours
