### ISSUE TITLE
Recruitment web app - administrator - CRUD job locations

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#20]

**Comment by jjjsss3** [comment]
2 hour - Create Migration and Model for Job locations
 Table for Job locations may be:
  - Country
  - Province/State
  - District
  - Ward
  - Detail Address
  (Association for job locations with another model will add after)

1 hour -  Implement Read action(Index)
2 hour - Implement Create Action with gem can provide address
1 hour - Implement Show and update action
1 hour -  Implement Delete action
 
Test, refactor code: 2 hours
Buffer : 3 hours
