### ISSUE TITLE
Recruitment web app - administrator - CRUD job tags

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#21]

**Comment by Priyarekah** [comment]
2 hour - Create Migration and Model for Job tags
Table for Job tags will include:
Country - String
Job Id - Integer
Job Category Id - Integer
Description - Text 

(Association for job tags will be with job locations and categories)
1 hour - Implement Read action(Index)
2 hour - Implement Create Action
1 hour - Implement Show and update action
1 hour - Implement Delete action

Test, refactor code: 2 hours
Buffer : 3 hours
