### ISSUE TITLE
Recruitment web app - administrator - CRUD job categories

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#22]

**Comment by longlh-dev** [comment]
2 hour - Create Migration and Model for Job Categories
Table for Job Categories may be:
- category_name
- category_description
- jobs_count ( depend on Job model, it will add later )
- category_status
(Association for job categories will be with  job model)
1 hour - Implement Read action(Index)
2 hour - Implement Create Action 
1 hour - Implement Show and update action
1 hour - Implement Delete action

Test, refactor code: 2 hours
Buffer : 3 hours
