### ISSUE TITLE
Recruitment web app - Implement admin layout

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#33]
```
Layout: https://prium.github.io/phoenix/v1.13.0/apps/e-commerce/admin/customers.html
Sidebar: https://dev.to/codeply/bootstrap-5-sidebar-examples-38pb
```
- Header
- Left sidebar

**Comment by KhoaNDAHopee** [comment]
@minhnguyennn lead

**Comment by khoadev2512** [comment]
Estimate:
- Thời gian research + thời gian design: 1h
- Thời gian code:
   + code left sidebars: 5h (Khoa)
   + code headers: 5h (Minh)
- Thời gian manual test: 1h
- Thời gian buffers: 1h
