### ISSUE TITLE
Recruitment web app - Implement customer layout

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#34]
```
https://prium.github.io/phoenix/v1.13.0/apps/e-commerce/landing/homepage.html
```
- Header
- Top menu
- Footer

**Comment by KhoaNDAHopee** [comment]
@hothanhdatsd lead

**Comment by hothanhdatsd** [comment]
Thời gian research + design: 2h
Thời gian code : 1 ngày
Thời gian viết unit test : 0
Thời gian viết manual test : 0
Thơi gian buffers : 2h
Header + Footer : Hoàn 
Top Menu : Đạt
