### ISSUE TITLE
Recruitment web app - Features

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#8]
+ Employer
    - Manage jobs
    - Integrate with another job-board (3rd party look like monters, careerbuilder)
    - Manage talents and their cv
    - Manage companies
    - Manage interviews (time, locations, notifications, examinations...)
    - Manage job's tags
    - Manage human resources
    - Search talents and send notifications to talents
+ Employee
    - Search jobs (by tags, companies, job's titles...)
    - Apply jobs
    - Manage their apply jobs
    - Manage cv
    - Manage profile
    - Rating for jobs, companies
    - Manage wish list

**Comment by tudeptrai1** [comment]
Em gửi database
![Untitled](https://github.com/HopeeSolutionsRuby/demo-app/assets/102434123/4be61450-c9c3-4ca8-9b6e-972b255c2f49)

**Comment by tudeptrai1** [comment]
Em gửi database ạ
![Untitled (1)](https://github.com/HopeeSolutionsRuby/demo-app/assets/102434123/af829bff-3a28-461e-8358-88c0326126e2)

**Comment by tunh-dev1** [comment]
Em gửi database ạ
![Untitled](https://github.com/HopeeSolutionsRuby/demo-app/assets/102434123/2e19a080-b64e-4bbd-9fe6-b550f02cf681)

**Comment by jjjsss3** [comment]
![recuitment](https://github.com/HopeeSolutionsRuby/demo-app/assets/73769239/ff28abfe-80f8-4b40-8699-838a95f946bf)
Em gui database a

**Comment by longlh-dev** [comment]
![rescuitmentdb1](https://github.com/HopeeSolutionsRuby/demo-app/assets/101177931/919a99f1-ca6f-4efe-b75f-a521f778f4a0)
em gui database a

**Comment by Priyarekah** [comment]
![recruitment_app](https://github.com/HopeeSolutionsRuby/demo-app/assets/103986792/725c6ddc-14b6-41b4-b6e0-f8a5c7d2331f)

**Comment by DucNguyen0812** [comment]
![recuitment(1)](https://github.com/HopeeSolutionsRuby/demo-app/assets/102718333/56eeac04-f1cc-4728-8828-75e4b8147c40)
